### ISSUE TITLE
can't get the migrations done

### ISSUE THREAD

**Issue by intrixius** [thehyve/arborist#1]
I have successfully deployed arborist with docker compose, but somehow the migrations are not done so the postgres DB is empty...
how should I do the migrations? inside the docker container...
BW,
Koen

**Comment by jochemb** [comment]
Hi Koen, 

sorry for the very slow response. Most of the work on the Arborist is actually in the related python library which does the heavy lifting (https://github.com/thehyve/tmtk). So we completely missed your question here. 

Have you succeeded in solving this issue?

Best,
Jochem

**Comment by intrixius** [comment]
That is indeed a slow response ;-)
I am no longer working on this project, so I will close the issue...
Anyhow, keep up the good work, because I know you guys make great stuff!
Greetings to Kees and Janneke as well ;-)
